hospital/Models/PatientReport.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace hospital.models
{
    public class PatientReport
    {
        [Key]
        public int PatientReport_Id { get; set; }
        public string Report_name { get; set; }
        public string Report_MedicationName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Report_Date { get; set; }
        public double cost { get; set; }
        public string prescription { get; set; }
        public int? Patient_ID { get; set; }
        [ForeignKey(nameof(Patient_ID))]
        public PatientAccount Patient { get; set; }
        public int? Doctor_ID { get; set; }
        [ForeignKey(nameof(Doctor_ID))]
        public DoctorAccount Doctor { get; set; }

    }
}

hospital/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hospital.connect;
using hospital.models;

namespace hospital.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly HospitalContext _context;

        public AppointmentsController(HospitalContext context)
        {
            _context = context;
        }

        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            var userMail = HttpContext.Session.GetString("UserId");
            if (HttpContext.Session.GetString("UserType") == "Doctor")
            {
                var hospitalContext = _context.Appointments.Include(a => a.Department).Include(a => a.Doctor).Include(a => a.Patient).Where(a => a.Doctor.Email == userMail).Include(a => a.Department).Include(a => a.Doctor).Include(a => a.Patient);
                return View(await hospitalContext.ToListAsync());
            }
            else
            {
                var hospitalContext = _context.Appointments.Include(a => a.Department).Include(a => a.Doctor).Include(a => a.Patient).Where(a => a.Patient.Email == userMail).Include(a => a.Department).Include(a => a.Doctor).Include(a => a.Patient);
                return View(await hospitalContext.ToListAsync());
            }

        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Department)
                .Include(a => a.Doctor)
                .Include(a => a.Patient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }
        
        // GET: Appointments/Create
        public IActionResult Create()
        {
            ViewData["Department_Id"] = new SelectList(_context.Departments, "Department_Id", "Department_Id");
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Name");
            ViewData["Patient_Id"] = new SelectList(_context.Accounts, "Patient_ID", "Email");
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Patient_name,Department_Id,Doctor_ID,Patient_Id,Appointment_Date,Phonenumber,Symptoms")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Department_Id"] = new SelectList(_context.Departments, "Department_Id", "Department_Id", appointment.Department_Id);
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Name", appointment.Doctor_ID);
            ViewData["Patient_Id"] = new SelectList(_context.Accounts, "Patient_ID", "Email", appointment.Patient_Id);
            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            ViewData["Department_Id"] = new SelectList(_context.Departments, "Department_Id", "Department_Id", appointment.Department_Id);
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Name", appointment.Doctor_ID);
            ViewData["Patient_Id"] = new SelectList(_context.Accounts, "Patient_ID", "Email", appointment.Patient_Id);
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Patient_name,Department_Id,Doctor_ID,Patient_Id,Appointment_Date,Phonenumber,Symptoms")] Appointment appointment)
        {
            if (id != appointment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Department_Id"] = new SelectList(_context.Departments, "Department_Id", "Department_Id", appointment.Department_Id);
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Name", appointment.Doctor_ID);
            ViewData["Patient_Id"] = new SelectList(_context.Accounts, "Patient_ID", "Email", appointment.Patient_Id);
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Department)
                .Include(a => a.Doctor)
                .Include(a => a.Patient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Appointments == null)
            {
                return Problem("Entity set 'HospitalContext.Appointments'  is null.");
            }
            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment != null)
            {
                _context.Appointments.Remove(appointment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(int id)
        {
          return (_context.Appointments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

hospital/Controllers/DoctorIndexController.cs
using hospital.connect;
using Microsoft.AspNetCore.Mvc;

namespace HospitalSystem.Controllers
{
    public class DoctorIndexController : Controller
    {
        private readonly HospitalContext context;

        public DoctorIndexController(HospitalContext con)
        {
            this.context = con;
        }
        public IActionResult DoctorIndex()
        {
            return View();
        }

        public IActionResult PatientReport()
        {
            return View();

        }
        public IActionResult Appointment()
        {
            return View();

        }

    }
}

hospital/Controllers/PatientReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hospital.connect;
using hospital.models;

namespace hospital.Controllers
{
    public class PatientReportsController : Controller
    {
        private readonly HospitalContext _context;

        public PatientReportsController(HospitalContext context)
        {
            _context = context;
        }

        // GET: PatientReports
        public async Task<IActionResult> Index()
        {
            var hospitalContext = _context.PatientReports.Include(p => p.Doctor).Include(p => p.Patient);
            return View(await hospitalContext.ToListAsync());
        }

        // GET: PatientReports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PatientReports == null)
            {
                return NotFound();
            }

            var patientReport = await _context.PatientReports
                .Include(p => p.Doctor)
                .Include(p => p.Patient)
                .FirstOrDefaultAsync(m => m.PatientReport_Id == id);
            if (patientReport == null)
            {
                return NotFound();
            }

            return View(patientReport);
        }

        // GET: PatientReports/Create
        public IActionResult Create()
        {
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Contact");
            ViewData["Patient_ID"] = new SelectList(_context.Accounts, "Patient_ID", "Email");
            return View();
        }

        // POST: PatientReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PatientReport_Id,Report_name,Report_MedicationName,Report_Date,cost,prescription,Patient_ID,Doctor_ID")] PatientReport patientReport)
        {
         //   if (ModelState.IsValid)
            {
                _context.Add(patientReport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Contact", patientReport.Doctor_ID);
            ViewData["Patient_ID"] = new SelectList(_context.Accounts, "Patient_ID", "Email", patientReport.Patient_ID);
            return View(patientReport);
        }

        // GET: PatientReports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PatientReports == null)
            {
                return NotFound();
            }

            var patientReport = await _context.PatientReports.FindAsync(id);
            if (patientReport == null)
            {
                return NotFound();
            }
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Contact", patientReport.Doctor_ID);
            ViewData["Patient_ID"] = new SelectList(_context.Accounts, "Patient_ID", "Email", patientReport.Patient_ID);
            return View(patientReport);
        }

        // POST: PatientReports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PatientReport_Id,Report_name,Report_MedicationName,Report_Date,cost,prescription,Patient_ID,Doctor_ID")] PatientReport patientReport)
        {
            if (id != patientReport.PatientReport_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patientReport);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientReportExists(patientReport.PatientReport_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Contact", patientReport.Doctor_ID);
            ViewData["Patient_ID"] = new SelectList(_context.Accounts, "Patient_ID", "Email", patientReport.Patient_ID);
            return View(patientReport);
        }

        // GET: PatientReports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PatientReports == null)
            {
                return NotFound();
            }

            var patientReport = await _context.PatientReports
                .Include(p => p.Doctor)
                .Include(p => p.Patient)
                .FirstOrDefaultAsync(m => m.PatientReport_Id == id);
            if (patientReport == null)
            {
                return NotFound();
            }

            return View(patientReport);
        }

        // POST: PatientReports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PatientReports == null)
            {
                return Problem("Entity set 'HospitalContext.PatientReports'  is null.");
            }
            var patientReport = await _context.PatientReports.FindAsync(id);
            if (patientReport != null)
            {
                _context.PatientReports.Remove(patientReport);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientReportExists(int id)
        {
          return (_context.PatientReports?.Any(e => e.PatientReport_Id == id)).GetValueOrDefault();
        }
    }
}

hospital/Views/PatientReports/Create.cshtml
@model hospital.models.PatientReport

@{
    // Layout = "/Views/Shared/_LayoutNoHeader.cshtml";

    ViewData["Title"] = "Create";
    Layout = null;
}
<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Mico</title>


    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- font awesome style -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <!-- nice select -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha256-mLBIhmBvigTFWPSCtvdu6a76T+3Xyt+K571hupeFLg4=" crossorigin="anonymous" />
    <!-- datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css">
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css/responsive.css" rel="stylesheet" />

</head>
<header class="header_section">
    <div class="header_top">
        <div class="container">
            <div class="contact_nav">
                <a href="">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    <span>
                        Call : +01 123455678990
                    </span>
                </a>
                <a href="">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                    <span>
                        Email : demo@gmail.com
                    </span>
                </a>
                <a href="">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <span>
                        Location
                    </span>
                </a>
            </div>
        </div>
    </div>
    <div class="header_bottom">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg custom_nav-container ">
                <a class="navbar-brand" href="index.html">
                    <img src="~/images/logo.png" alt="">
                </a>


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class=""> </span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="d-flex mr-auto flex-column flex-lg-row align-items-center">
                        <ul class="navbar-nav  ">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DoctorIndex" asp-action="DoctorIndex">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Appoitment</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PatientReports" asp-action="Create">Patient Report</a>
                            </li>
                        </ul>
                    </div>

            </nav>
        </div>
    </div>
</header>


<h1>Create</h1>

<h4>PatientReport</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Report_name" class="control-label"></label>
                <input asp-for="Report_name" class="form-control" />
                <span asp-validation-for="Report_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Report_MedicationName" class="control-label"></label>
                <input asp-for="Report_MedicationName" class="form-control" />
                <span asp-validation-for="Report_MedicationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Report_Date" class="control-label"></label>
                <input asp-for="Report_Date" class="form-control" />
                <span asp-validation-for="Report_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cost" class="control-label"></label>
                <input asp-for="cost" class="form-control" />
                <span asp-validation-for="cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="prescription" class="control-label"></label>
                <input asp-for="prescription" class="form-control" />
                <span asp-validation-for="prescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient_ID" class="control-label"></label>
                <select asp-for="Patient_ID" class ="form-control" asp-items="ViewBag.Patient_ID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Doctor_ID" class="control-label"></label>
                <select asp-for="Doctor_ID" class ="form-control" asp-items="ViewBag.Doctor_ID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


<!-- jQery -->
<script src="~/js/jquery-3.4.1.min.js"></script>
<!-- bootstrap js -->
<script src="~/js/bootstrap.js"></script>
<!-- nice select -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js" integrity="sha256-Zr3vByTlMGQhvMfgkQ5BtWRSKBGa2QlspKYJnkjZTmo=" crossorigin="anonymous"></script>
<!-- owl slider -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<!-- datepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
<!-- custom js -->
<script src="~/js/custom.js"></script>

hospital/Views/PatientReports/Delete.cshtml
@model hospital.models.PatientReport

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PatientReport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Report_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Report_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Report_MedicationName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Report_MedicationName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Report_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Report_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Patient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Patient.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Doctor.Doctor_Contact)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PatientReport_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

hospital/Views/PatientReports/Details.cshtml
@model hospital.models.PatientReport

@{
    ViewData["Title"] = "Details";
    Layout = "~/V";
}

<h1>Details</h1>

<div>
    <h4>PatientReport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Report_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Report_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Report_MedicationName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Report_MedicationName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Report_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Report_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Patient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Patient.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Doctor.Doctor_Contact)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PatientReport_Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

hospital/Views/PatientReports/Edit.cshtml
@model hospital.models.PatientReport

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>PatientReport</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PatientReport_Id" />
            <div class="form-group">
                <label asp-for="Report_name" class="control-label"></label>
                <input asp-for="Report_name" class="form-control" />
                <span asp-validation-for="Report_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Report_MedicationName" class="control-label"></label>
                <input asp-for="Report_MedicationName" class="form-control" />
                <span asp-validation-for="Report_MedicationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Report_Date" class="control-label"></label>
                <input asp-for="Report_Date" class="form-control" />
                <span asp-validation-for="Report_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cost" class="control-label"></label>
                <input asp-for="cost" class="form-control" />
                <span asp-validation-for="cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="prescription" class="control-label"></label>
                <input asp-for="prescription" class="form-control" />
                <span asp-validation-for="prescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient_ID" class="control-label"></label>
                <select asp-for="Patient_ID" class="form-control" asp-items="ViewBag.Patient_ID"></select>
                <span asp-validation-for="Patient_ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Doctor_ID" class="control-label"></label>
                <select asp-for="Doctor_ID" class="form-control" asp-items="ViewBag.Doctor_ID"></select>
                <span asp-validation-for="Doctor_ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

hospital/Views/PatientReports/Index.cshtml
@model IEnumerable<hospital.models.PatientReport>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Report_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Report_MedicationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Report_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.prescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patient)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doctor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Report_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Report_MedicationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Report_Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patient.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor.Doctor_Contact)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PatientReport_Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PatientReport_Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PatientReport_Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>