hospital/Models/Appointment.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Numerics;

namespace hospital.models

{
    public class Appointment
    {

        public int Id { get; set; }
        public string Patient_name { get; set; }


        public int? Department_Id { get; set; }
        [ForeignKey(nameof(Department_Id))]
        public Department? Department { get; set; }


        public int? Doctor_ID { get; set; }
        [ForeignKey(nameof(Doctor_ID))]
        public DoctorAccount? Doctor { get; set; }
        public int? Patient_Id { get; set; }
        [ForeignKey(nameof(Patient_Id))]
        public PatientAccount? Patient { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime Appointment_Date { get; set; }


        public string? Phonenumber { get; set; }
        public string? Symptoms { get; set; }



    }
}

hospital/Models/PatientReport.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace hospital.models
{
    public class PatientReport
    {
        [Key]
        public int PatientReport_Id { get; set; }
        public string Report_name { get; set; }
        public string Report_MedicationName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Report_Date { get; set; }
        public double cost { get; set; }
        public string prescription { get; set; }
        public int? Patient_ID { get; set; }
        [ForeignKey(nameof(Patient_ID))]
        public PatientAccount Patient { get; set; }
        public int? Doctor_ID { get; set; }
        [ForeignKey(nameof(Doctor_ID))]
        public DoctorAccount Doctor { get; set; }

    }
}

hospital/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hospital.connect;
using hospital.models;

namespace hospital.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly HospitalContext _context;

        public AppointmentsController(HospitalContext context)
        {
            _context = context;
        }

        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            var userMail = HttpContext.Session.GetString("UserId");
            if (HttpContext.Session.GetString("UserType") == "Doctor")
            {
                var hospitalContext = _context.Appointments.Include(a => a.Department).Include(a => a.Doctor).Include(a => a.Patient).Where(a => a.Doctor.Email == userMail).Include(a => a.Department).Include(a => a.Doctor).Include(a => a.Patient);
                return View(await hospitalContext.ToListAsync());
            }
            else
            {
                var hospitalContext = _context.Appointments.Include(a => a.Department).Include(a => a.Doctor).Include(a => a.Patient).Where(a => a.Patient.Email == userMail).Include(a => a.Department).Include(a => a.Doctor).Include(a => a.Patient);
                return View(await hospitalContext.ToListAsync());
            }

        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Department)
                .Include(a => a.Doctor)
                .Include(a => a.Patient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }
        
        // GET: Appointments/Create
        public IActionResult Create()
        {
            ViewData["Department_Id"] = new SelectList(_context.Departments, "Department_Id", "Department_Id");
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Name");
            ViewData["Patient_Id"] = new SelectList(_context.Accounts, "Patient_ID", "Email");
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Patient_name,Department_Id,Doctor_ID,Patient_Id,Appointment_Date,Phonenumber,Symptoms")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Department_Id"] = new SelectList(_context.Departments, "Department_Id", "Department_Id", appointment.Department_Id);
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Name", appointment.Doctor_ID);
            ViewData["Patient_Id"] = new SelectList(_context.Accounts, "Patient_ID", "Email", appointment.Patient_Id);
            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            ViewData["Department_Id"] = new SelectList(_context.Departments, "Department_Id", "Department_Id", appointment.Department_Id);
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Name", appointment.Doctor_ID);
            ViewData["Patient_Id"] = new SelectList(_context.Accounts, "Patient_ID", "Email", appointment.Patient_Id);
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Patient_name,Department_Id,Doctor_ID,Patient_Id,Appointment_Date,Phonenumber,Symptoms")] Appointment appointment)
        {
            if (id != appointment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Department_Id"] = new SelectList(_context.Departments, "Department_Id", "Department_Id", appointment.Department_Id);
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Name", appointment.Doctor_ID);
            ViewData["Patient_Id"] = new SelectList(_context.Accounts, "Patient_ID", "Email", appointment.Patient_Id);
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Department)
                .Include(a => a.Doctor)
                .Include(a => a.Patient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Appointments == null)
            {
                return Problem("Entity set 'HospitalContext.Appointments'  is null.");
            }
            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment != null)
            {
                _context.Appointments.Remove(appointment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(int id)
        {
          return (_context.Appointments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

hospital/Controllers/PatientIndexController.cs
using hospital.connect;
using Microsoft.AspNetCore.Mvc;

namespace HospitalSystem.Controllers
{
    public class PatientIndexController : Controller
    {
        private readonly HospitalContext context;

        public PatientIndexController(HospitalContext con)
        {
            this.context = con;
        }

        
        public IActionResult PatientIndex()
        {

            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Treatment()
        {
            return View();
        }

        public IActionResult Doctors()
        {
            return View();
        }
        public IActionResult Appointments()
        {
            return View();
        }
        public IActionResult PatientReport()
        {
            return View();
        }

    }
}

hospital/Controllers/PatientReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hospital.connect;
using hospital.models;

namespace hospital.Controllers
{
    public class PatientReportsController : Controller
    {
        private readonly HospitalContext _context;

        public PatientReportsController(HospitalContext context)
        {
            _context = context;
        }

        // GET: PatientReports
        public async Task<IActionResult> Index()
        {
            var hospitalContext = _context.PatientReports.Include(p => p.Doctor).Include(p => p.Patient);
            return View(await hospitalContext.ToListAsync());
        }

        // GET: PatientReports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PatientReports == null)
            {
                return NotFound();
            }

            var patientReport = await _context.PatientReports
                .Include(p => p.Doctor)
                .Include(p => p.Patient)
                .FirstOrDefaultAsync(m => m.PatientReport_Id == id);
            if (patientReport == null)
            {
                return NotFound();
            }

            return View(patientReport);
        }

        // GET: PatientReports/Create
        public IActionResult Create()
        {
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Contact");
            ViewData["Patient_ID"] = new SelectList(_context.Accounts, "Patient_ID", "Email");
            return View();
        }

        // POST: PatientReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PatientReport_Id,Report_name,Report_MedicationName,Report_Date,cost,prescription,Patient_ID,Doctor_ID")] PatientReport patientReport)
        {
         //   if (ModelState.IsValid)
            {
                _context.Add(patientReport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Contact", patientReport.Doctor_ID);
            ViewData["Patient_ID"] = new SelectList(_context.Accounts, "Patient_ID", "Email", patientReport.Patient_ID);
            return View(patientReport);
        }

        // GET: PatientReports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PatientReports == null)
            {
                return NotFound();
            }

            var patientReport = await _context.PatientReports.FindAsync(id);
            if (patientReport == null)
            {
                return NotFound();
            }
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Contact", patientReport.Doctor_ID);
            ViewData["Patient_ID"] = new SelectList(_context.Accounts, "Patient_ID", "Email", patientReport.Patient_ID);
            return View(patientReport);
        }

        // POST: PatientReports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PatientReport_Id,Report_name,Report_MedicationName,Report_Date,cost,prescription,Patient_ID,Doctor_ID")] PatientReport patientReport)
        {
            if (id != patientReport.PatientReport_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patientReport);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientReportExists(patientReport.PatientReport_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Doctor_ID"] = new SelectList(_context.Doctors, "Doctor_Id", "Doctor_Contact", patientReport.Doctor_ID);
            ViewData["Patient_ID"] = new SelectList(_context.Accounts, "Patient_ID", "Email", patientReport.Patient_ID);
            return View(patientReport);
        }

        // GET: PatientReports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PatientReports == null)
            {
                return NotFound();
            }

            var patientReport = await _context.PatientReports
                .Include(p => p.Doctor)
                .Include(p => p.Patient)
                .FirstOrDefaultAsync(m => m.PatientReport_Id == id);
            if (patientReport == null)
            {
                return NotFound();
            }

            return View(patientReport);
        }

        // POST: PatientReports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PatientReports == null)
            {
                return Problem("Entity set 'HospitalContext.PatientReports'  is null.");
            }
            var patientReport = await _context.PatientReports.FindAsync(id);
            if (patientReport != null)
            {
                _context.PatientReports.Remove(patientReport);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientReportExists(int id)
        {
          return (_context.PatientReports?.Any(e => e.PatientReport_Id == id)).GetValueOrDefault();
        }
    }
}

hospital/Views/PatientIndex/About.cshtml
@{
    Layout = "/Views/Shared/_LayoutNoHeader.cshtml";
    ViewData["Title"] = "About Page";

}

<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Mico</title>


    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- font awesome style -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <!-- nice select -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha256-mLBIhmBvigTFWPSCtvdu6a76T+3Xyt+K571hupeFLg4=" crossorigin="anonymous" />
    <!-- datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css">
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="header_top">
                <div class="container">
                    <div class="contact_nav">
                        <a href="">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <span>
                                Call : +01 123455678990
                            </span>
                        </a>
                        <a href="">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                            <span>
                                Email : demo@gmail.com
                            </span>
                        </a>
                        <a href="">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                            <span>
                                Location
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="header_bottom">
                <div class="container-fluid">
                    <nav class="navbar navbar-expand-lg custom_nav-container ">
                        <a class="navbar-brand" href="index.html">
                            <img src="~/images/logo.png" alt="">
                        </a>
                        </a>

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class=""> </span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <div class="d-flex mr-auto flex-column flex-lg-row align-items-center">
                                <ul class="navbar-nav  ">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="PatientIndex" asp-action="PatientIndex">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="PatientIndex" asp-action="About">About</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="PatientIndex" asp-action="Treatment">Treatment</a>
                                    </li>
                                   
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="PatientIndex" asp-action="PatientReport">Patient Report</a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </nav>
                </div>
            </div>
        </header>
        <!-- end header section -->
    </div>


    <!-- about section -->

    <section class="about_section layout_padding">
        <div class="container  ">
            <div class="row">
                <div class="col-md-6 ">
                    <div class="img-box">
                        <img src="~/images/about-img.jpg" alt="">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="detail-box">
                        <div class="heading_container">
                            <h2>
                                About <span>Hospital</span>
                            </h2>
                        </div>
                        <p>
                            has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors
                        </p>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- end about section -->
    <!-- info section -->
    <section class="info_section ">
        <div class="container">
            <div class="info_top">
                <div class="info_logo">
                    <a href="">
                        <img src="~/images/logo.png" alt="">
                    </a>
                </div>
                <div class="info_form">
                    <form action="">
                        <input type="email" placeholder="Your email">
                        <button>
                            Subscribe
                        </button>
                    </form>
                </div>
            </div>
            <div class="info_bottom layout_padding2">
                <div class="row info_main_row">
                    <div class="col-md-6 col-lg-3">
                        <h5>
                            Address
                        </h5>
                        <div class="info_contact">
                            <a href="">
                                <i class="fa fa-map-marker" aria-hidden="true"></i>
                                <span>
                                    Location
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-phone" aria-hidden="true"></i>
                                <span>
                                    Call +01 1234567890
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-envelope"></i>
                                <span>
                                    demo@gmail.com
                                </span>
                            </a>
                        </div>
                        <div class="social_box">
                            <a href="">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-instagram" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="info_links">
                            <h5>
                                Useful link
                            </h5>
                            <div class="info_links_menu">
                                <a href="index.html">
                                    Home
                                </a>
                                <a class="active" href="about.html">
                                    About
                                </a>
                                <a href="treatment.html">
                                    Treatment
                                </a>
                                <a href="doctor.html">
                                    Doctors
                                </a>
                                <a href="testimonial.html">
                                    Testimonial
                                </a>
                                <a href="contact.html">
                                    Contact us
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="info_post">
                            <h5>
                                LATEST POSTS
                            </h5>
                            <div class="post_box">
                                <div class="img-box">
                                    <img src="~/images/post1.jpg" alt="">
                                </div>
                                <p>
                                    Normal
                                    distribution
                                </p>
                            </div>
                            <div class="post_box">
                                <div class="img-box">
                                    <img src="~/images/post2.jpg" alt="">
                                </div>
                                <p>
                                    Normal
                                    distribution
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="info_post">
                            <h5>
                                News
                            </h5>
                            <div class="post_box">
                                <div class="img-box">
                                    <img src="~/images/post3.jpg" alt="">
                                </div>
                                <p>
                                    Normal
                                    distribution
                                </p>
                            </div>
                            <div class="post_box">
                                <div class="img-box">
                                    <img src="~/images/post4.png" alt="">
                                </div>
                                <p>
                                    Normal
                                    distribution
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end info_section -->
    <!-- footer section -->
    <footer class="footer_section">
        <div class="container">
            <p>
                &copy; <span id="displayYear"></span> All Rights Reserved By
                <a href="https://html.design/">Free Html Templates</a>
            </p>
        </div>
    </footer>
    <!-- footer section -->
    <!-- jQery -->
    <script src="js/jquery-3.4.1.min.js"></script>
    <!-- bootstrap js -->
    <script src="js/bootstrap.js"></script>
    <!-- nice select -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js" integrity="sha256-Zr3vByTlMGQhvMfgkQ5BtWRSKBGa2QlspKYJnkjZTmo=" crossorigin="anonymous"></script>
    <!-- owl slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <!-- datepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
    <!-- custom js -->
    <script src="js/custom.js"></script>


</body>

</html>

hospital/Views/PatientIndex/Appointment.cshtml
@{
    Layout = "/Views/Shared/_LayoutNoHeader.cshtml";
    ViewData["Title"] = "Appoitment Page";

}

hospital/Views/PatientIndex/PatientReport.cshtml
@{
    Layout = "/Views/Shared/_LayoutNoHeader.cshtml";
    ViewData["Title"] = "Patient Report Page";

}